[workspace]
members = ["csbindgen", "csbindgen-tests"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
csbindgen = { path = "csbindgen" }

syn = { version = "2" }
regex = "1.12"
bitflags = "2.10"
cc = "1.2"
bindgen = "0.72"
